# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            MTurgeon
tagline:          'Maxime Turgeon'
description:      'My personal webpage'
url:              http://turgeonmaxime.github.io

author:
  name:           'Maxime Turgeon'
  url:            https://twitter.com/mturg1989

paginate:         5

# Custom vars
version:          0.0.1.9000

github:
  repo:           https://github.com/turgeonmaxime/turgeonmaxime.github.io
