# Dependencies
markdown:         kramdown
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "strikethrough", "superscript", "with_toc_data"]
pygments:         true

# Permalinks
permalink:        /:title

# Setup
title:            MTurgeon
tagline:          'Maxime Turgeon'
description:      'My personal webpage'
url:              http://turgeonmaxime.github.io

author:
  name:           'Maxime Turgeon'
  url:            https://twitter.com/mturg1989

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/turgeonmaxime/turgeonmaxime.github.io

excerpt_separator: <!--more-->
